### ISSUE TITLE
Update server install instructions to include minima repos in certain cases

### ISSUE THREAD

**Issue by crichID** [githubtraining/github-pages#29]
## Bug Report

**Current behavior**

As reported by a user:

> In the GitHub Pages course, It has you update your user ID in the config.  It then uses that to create a link to your GitHub profile on the bottom of the blog post page.  I think that link should point to your GHE instance instead of GitHub.com if you’re running the course from GHES.

The minima theme automatically generates the link to point to github.com in: https://github.com/jekyll/minima/blob/aeab39123d8b5f853bc2427c0d72318a2b5055bd/_includes/social.html#L8

**Possible solution**

We could look at the other packaged themes: https://pages.github.com/themes/ to see if switching would fix the problem. 

/cc @amyschoen @brianamarie @hectorsector

**Comment by brianamarie** [comment]
> We could look at the other packaged themes: https://pages.github.com/themes/ to see if switching would fix the problem.

🤔 Hmm.. I like the idea of supported themes, but it looks like Minima _should_ be supported.

As a possible alternative, it looks like GitHub Pages [supports other remote themes](https://help.github.com/en/enterprise/2.14/user/articles/adding-a-jekyll-theme-to-your-github-pages-site). 

>  To activate any other open source Jekyll theme hosted on GitHub Enterprise, type remote_theme: followed by the name of the theme (as shown in the README or other documentation in the theme's source repository).

Would it be possible to re-create the `minima` repository inside of the GHES instance, then alter the instructions to ask for a `remote-theme` of `org/minima`?

**Comment by amyschoen** [comment]
I could likely get that going.  I had to fix the theming and references on the initial course repo for the GitHub for Developers class to work with both GHES and .com since it wasn't properly theming on .com.  That could be used for a reference that we should be able to get working for both.  The plus side of that is if we can figure that out, no instruction change would be needed.
