### ISSUE TITLE
Homepage titles printed twice

### ISSUE THREAD

**Issue by yhkee0404** [githubtraining/github-pages#36]
## Bug Report

**Current behavior**
Homepage titles are redundantly printed twice. The course description also shows a screen capture where the page title `Welcome to my blog` is printed twice.

https://github.com/githubtraining/github-pages/blob/6db77addee7836337a855b2a7514946c6157047b/course-details.md#L21-L25

![Screenshot_2020-02-25 Welcome to my blog](https://user-images.githubusercontent.com/1221423/75267083-224fd180-57a8-11ea-8acf-64c1ee6d950f.png) 

**Reproduction**
Steps to reproduce the behavior in the course:
1. Follow the course steps up to **Step 4: Customize Site Details**, keeping `index.md` beginning with a heading. For example, the default file begins with `# Welcome to my blog`.
2. Click the link to the published page, represented as ``[here]({{ deploymentUrl }})``: https://github.com/githubtraining/github-pages/blob/6db77addee7836337a855b2a7514946c6157047b/responses/03_change-theme.md#L1-L3
3. See the beginning heading, e.g. `Welcome to my blog`, replicating itself twice.

**Expected behavior**
It is enough to print it just once like [this](https://yhkee0404.github.io/github-pages-with-jekyll/):
![B4DBB53D-91A9-4E50-A0D8-3D25E3CAD999](https://user-images.githubusercontent.com/29868089/113475869-c1b6bc00-94b2-11eb-9e3f-6442e8c65f24.jpeg)

**Possible solution**
Replace the default beginning heading `# Welcome to my blog` in `index.md` with a front matter like this:
```diff
-# Welcome to my blog
+---
+title: “Welcome to my blog”
+---

I’m glad you are here. I plan to talk about …
```
Or just delete the number sign (#) of the beginning heading to make sure that `index.md` do not begin with a heading.

Additionally, add an instruction like “Write your homepage title in a front matter.” or a warning like “Make sure that `index.md` do not begin with a heading without a page title front matter.” to `responses/01_update-index.md` where users update `index.md`.
https://github.com/githubtraining/github-pages/blob/6db77addee7836337a855b2a7514946c6157047b/responses/01_update-index.md#L7-L13

**Additional context**
I found the same issue and solution [here](https://talk.jekyllrb.com/t/title-derived-from-heading-appears-twice-on-top-of-page/1686) and [here](https://github.com/mmistakes/minimal-mistakes/issues/1618#issue-312563584).

I also made a [post](https://github.community/t/github-pages-takes-homepage-titles-from-beginning-headings/172297/1) on Github Community Forum.

**Comment by brianamarie** [comment]
Thank you so much, @yhkee0404! This looks like a great improvement. Would you be willing to submit pull requests with your suggested improvements?

**Comment by yhkee0404** [comment]
Thank you a billion for giving me this wonderful chance, @brianamarie! It was the best to meet you. Now I feel really connected to the whole world through GitHub. Thanks again for your warm welcome! 😂
